[MODEL]

# Embedding Dimensions
embed_dim = 400        # Token embedding dimensionality (size of word vectors)
hidden_dim = 200       # Hidden dimension of the LSTM layer

# Encoder Selection
encoder_type = lstm   # Choose: 'lstm' or 'HooshvareLab/bert-fa-zwnj-base'

# Character-Level Convolutional Neural Network (CharCNN)
char_dim = 8           # Character embedding dimensionality
char_filters = 50       # Number of filters in the CharCNN
char_pad_size = 15      # Maximum character input length per token

# Distance Representation
distance_dim = 20      # Dimensionality of distance embeddings

# lstm settings
n_lstm_layers = 2

[TRAINING]

# Training Parameters
epochs = 150                # Number of training epochs
eval_interval = 20          # Evaluate model every N epochs
max_sentences_per_doc = 50  # Maximum sentences per document (for LSTM)

# Data Loading (Steps/Batches per Epoch)
mehr_steps = 100         # Batches per epoch for Mehr corpus
rcdat_steps = 100        # Batches per epoch for RCDAT corpus

# Validation and Optimization
dev_size = 0.1           # Fraction of data used for validation
lr = 1e-3                # Learning rate
scheduler_step_size = 100 # Learning rate scheduler step size
scheduler_gamma = 0.001   # Learning rate decay factor


# Scoring Layers
mention_score_hidden_dim = 150  # Hidden dimension in mention scoring layers
pairwise_score_hidden_dim = 150 # Hidden dimension in pairwise scoring layers

# Dropout
lstm_dropout = 0.2       # Dropout for LSTM outputs (DocumentEncoder)
emb_dropout = 0.5       # Dropout for token embeddings (DocumentEncoder)
score_dropout = 0.2     # Dropout in the Score module


[DATA]

# Corpus Selection (Choose ONE)
corpus_type = Mehr       # 'Mehr' or 'RCDAT'

# Data Paths
rcdat_corpus_path_train = data/RCDAT/train-dev/
rcdat_corpus_path_test = data/RCDAT/test/
mehr_corpus_path_train = data/Mehr/train-dev/
mehr_corpus_path_test = data/Mehr/test/

# Model Storage
model_address = data/model     # Directory to save/load model checkpoints

# Mention Hyperparameters
k_antecedents = 250 # Maximum number of previous antecedents to consider
