[MODEL]
# Encoder type === can choose between ['lstm','HooshvareLab/bert-fa-zwnj-base']
encoder_type = lstm

# lstm hyperparameters
max_sentences_per_doc = 50
hidden_dim = 200

# char_cnn
char_dim = 8
char_filters = 50
distance_dim = 20

# span settings
embed_dim = 400

[TRAINING]
# Training hyperparameter
epochs = 150
eval_interval = 20
dev_size = 0.1

# Number of documents per epoch to train
mehr_steps = 100
rcdat_steps = 100

# optimizer and scheduler settings
lr = 1e-3
scheduler_step_size = 100
scheduler_gamma = 0.001

[DATA]
# corpus type choose between [Mehr,RCDAT]
corpus_type = Mehr

# RCDAT path
rcdat_corpus_path_train = data/RCDAT/train-dev/
rcdat_corpus_path_test = data/RCDAT/test/

# Mehr path
mehr_corpus_path_train = data/Mehr/train-dev/
mehr_corpus_path_test = data/Mehr/test/

# Model path
model_address = data/model