[MODEL]
# Word embedding dimensionality for custom
embed_dim = 400
# Hidden dimension of the LSTM layer (typically half or equal to embed_dim)
hidden_dim = 200
# Encoder type === can choose between ['lstm','HooshvareLab/bert-fa-zwnj-base']
encoder_type = lstm
# Character embedding dimensionality
char_dim = 8
# Number of filters in the CharCNN layer
char_filters = 50
# Dimensionality for distance embeddings
distance_dim = 20

[TRAINING]
# Number of epochs to train for (recommended range: 10-100)
epochs = 20
# eval interval for training
eval_interval = 5
# Maximum sentences per document (for LSTM only, helps control memory usage)
max_sentences_per_doc = 50
# Number of documents per epoch to train
mehr_steps = 3
rcdat_steps = 100
# Fraction of corpus to use for development (0.1 = 10%)
dev_size = 0.2
# Learning rate for the optimizer
lr = 1e-3
# step size for the scheduler
scheduler_step_size = 100
# gamma value for the scheduler
scheduler_gamma = 0.001


[DATA]
# corpus type Mehr, RCDAT
corpus_type = Mehr
# Path to the training corpus (should be split into train and dev) (For RCDAT )
rcdat_corpus_path_train = data/RCDAT/train-dev/
# Path to the training corpus (should be split into train and dev) (For Mehr )
mehr_corpus_path_train = data/Mehr/train-dev/
# Path to the test corpus (used for final evaluation)  (For Mehr )
mehr_corpus_path_test = data/Mehr/test/
# path of test and train for RCDATA only
rcdat_corpus_path_test = data/RCDAT/test/